project:
  type: book
  output-dir: docs

book:
  title: "Data Analysis With R"
  author: "Samuel Blay Nguah"
  date: today
  cover-image: R-Logo.jpg
  favicon: R-logo.jpeg
  reader-mode: false
  page-navigation: true
  cover-image-alt: "Logo"
  sidebar: 
    title: Contents
    search: true
    style: docked
  page-footer:
    background: light
    center: "Compiled by: Dr Samuel Blay Nguah"
  chapters:
    - index.qmd
    - introduction.qmd
    - data-importation.qmd
    - data-types.qmd
    - data-wrangling.qmd
    - data-cleaning.qmd
    - eda.qmd
    - descriptive-stats-continuous.qmd
    - descriptive-stats-categorical.qmd
    - analysis-of-continuous data.qmd
    - analysis-of-categorical-data.qmd
    - risk-and-odds.qmd
    - normality.qmd
    - hypothesis-testing.qmd
    - confounding-and-interaction.qmd
    - diagnostic-tests.qmd
    - roc-analysis.qmd
    - part: "<span style='font-weight:bold; color: black;'>Correlation</span>"
      chapters: 
        - correlation.qmd
    - part: "<span style='font-weight:bold; color: black;'>Linear Regression</span>"
      chapters: 
        - lin-reg-single-categorical.qmd
        - lin-reg-single-continuous.qmd
        - lin-reg-cont-categorical.qmd
        - lin-reg-multivariate.qmd
        - lin-reg-model-selection.qmd
        - linear-regression.qmd
    - part: "<span style='font-weight:bold; color: black;'>Analysis of Variance</span>"
      chapters: 
        - anova-oneway.qmd
        - anova-twoway.qmd
        - ancova.qmd
    - part: "<span style='font-weight:bold; color: black;'>Logistic Regression</span>"
      chapters: 
        - log-reg-single-categorical.qmd
        - log-reg-single-continuous.qmd
        - log-reg-cont-categorical.qmd
        - log-reg-multivariate.qmd
        - log-reg-model-selection.qmd
        - logistic-regression.qmd
    - part: "<span style='font-weight:bold; color: black;'>Ordinal Logistic Regression</span>"
      chapters:
        - ord-log-reg-single-categorical.qmd
        - ord-log-reg-single-continuous.qmd
        - ord-log-reg-cont-categorical.qmd
        - ord-log-reg-multivariate.qmd
    - part: "<span style='font-weight:bold; color: black;'>Survival Analysis</span>"
      chapters: 
        - survival-analysis.qmd
        - cox-regression.qmd
    - part: "<span style='font-weight:bold; color: black;'>Missiing Data</span>"
      chapters: 
        - missing-data.qmd
    - part: "<span style='font-weight:bold; color: black;'>Generalised Additive Modelling</span>"
      chapters: 
        - gam-single-categorical.qmd
        - gam-single-continuous.qmd
        - gam-multivariate.qmd
    - part: "<span style='font-weight:bold; color: black;'>Polynomial Regression</span>"
      chapters: 
        - poly-single-categorical.qmd
        - poly-single-continuous.qmd
        - poly-multivariate.qmd
    - part: "<span style='font-weight:bold; color: black;'>GQuantile Regression</span>"
      chapters: 
        - qr-single-categorical.qmd
        - qr-single-continuous.qmd
        - qr-multivariate.qmd
    - part: "<span style='font-weight:bold; color: black;'>Specific Packages</span>"
      chapters: 
        - pkg-dplyr.qmd
        - pkg-gtsummary.qmd
        - pkg-nlme.qmd
    - part: "<span style='font-weight:bold; color: black;'>Sample Size</span>"
      chapters: 
        - ss-matched-case-control.qmd
        - ss-comparing-two-means.qmd
        - ss-single-mean-to-reference-value.qmd
    - part: "<span style='font-weight:bold; color: black;'>Graphics</span>"
      chapters: 
        - gr-histogram.qmd
        - gr-densityplot.qmd
        - gr-boxplot.qmd
        - gr-barplot.qmd
        - gr-scatter.qmd
        - gr-line-plot.qmd
        - gr-curvelinear-plot.qmd
        - gr-forest-plot.qmd
        - gr-followup-plot.qmd
        - gr-venn-diagram.qmd
        - gr-population-pyramid.qmd
        - gr-lollipop.qmd
        - gr-miscellaneous.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    mainfont: Times New Roman
    code-fold: true
    theme: 
        - cosmo
        - BookTheme.scss
        
  pdf:
    documentclass: scrreprt

editor: visual

