---
title: "Venn Diagram"
---

```{r}
#| echo: false
#| message: false

library(tidyverse)
```

```{r}
df <- 
    tibble(
        x = c(1,2,3), 
        y = c(2,3.5,2), 
        lab1 = c("A","B","C"), 
        counts = 1:3)

df %>% 
    ggplot() +
    ggforce::geom_circle(
        aes(x0 = x, y0 = y, r = 1.4, fill = lab1), 
        alpha = .3, 
        size = 1, 
        colour = 'grey') +
    coord_fixed() +
    theme_void() +
    scale_fill_manual(values = c('cornflowerblue', 'firebrick',  'gold')) +
    scale_colour_manual(values = c('cornflowerblue', 'firebrick', 'gold'), 
                        guide = "none") +
    labs(fill = NULL, title = "My Venn Diagram I") + 
     annotate("text", 
              x = c(2, 3.5, 2.7, 1.2,   2,  2, 0.3), 
              y = c(4,   2, 2.7, 2.8, 2.5, 1.5, 1.8), 
              label = 1:7, size = 5, fontface = "bold") +
    theme(
        plot.title = element_text(
            hjust = 0.5, 
            family = "serif", 
            face = "bold", 
            size = 16, 
            colour = "red"),
          legend.position = 'bottom')
```
