---
title: "Matched Case-Control"
bibliography: references.bib
---

## Objective

To determine if being HIV positive (exposure) is associated with malnutrition (outcome) in children
on admission at a specialized nutritional rehabilitation center. A researcher intends to conduct a
matched case-control study he selects children with malnutrition and matches them to controls of
children without malnutrition at a ratio of 1:2.

## Hypothesis

$H_0$: There is no association between being malnourished and being HIV positive

## Formula

We use the formula below by @wang2020.

$$
n = (\frac{Z_{\alpha/2} + Z_\beta}{P_1 - P_2})^2 \times (1 + \frac{1}{k})
$$

Where:

-   $n$ is the number of matched pairs needed
-   $Z_{\alpha/2}$ is the critical value of the standard normal distribution at the desired
    significance level such that a 95% confidence level will correspond to 1.96
-   $Z_{\beta}$ is the critical value of the standard normal distribution at the desired power such
    that an 80% power will correspond to a value of 0.84.
-   $P_1$ is the proportion of exposure in cases. This can be obtained from similar prior studies
-   $P_0$ is the proportion of exposure in controls, This can be obtained from similar prior studies
-   $k$ is the number of controls per case such that for a 1:1 match $k$ =1

## Determination

Assuming in the literature the proportion of HIV positive in non-malnourished children ( $P_0$) was
0.25 and that for malnourished children ($P_1$) was 0.3. Also, the investigator decides the use a
95% confidence interval and a power of 80%. The sample size is determined as below

```{r}
#| echo: false
#| include: false
#| message: false

p0 <- 0.25        # True proportion
p1 <- 0.3        # Null hypothesis proportion
alpha <- 0.05
beta <- 0.20
k <- 2
n <- (((qnorm(1-alpha/2) + qnorm(1-beta))/(p1-p0))^2)*(1 + 1/k)
n <- ceiling(n)
n
```

$$
n = (\frac{1.96 + 0.84}{0.3 - 0.25})^2 \times (1 + \frac{1}{2})
$$

Thus a minimum total of `r n` study subjects will be included. This will consist of
`r ceiling(n-n*1/(k+1))` controls and `r ceiling(n*1/(k+1))` cases.
